### ISSUE TITLE
Set user agent to include the string "littleBits"

### ISSUE THREAD

**Issue by heavypennies** [littlebits/bitlab-voteview#21]
In order for us to ignore tracking robots, we need a clear set of user agents to exclude.  In this case, please add the string "littleBits" to the user agent of this service.

**Comment by jasonkuhrt** [comment]
User Agent is supposed to represent the tool responsible for making the requests. I would prefer a HTTP customer header metadata solution. For example:

```
X-Organization: littleBits
X-App: Voteview
```
